2018-10-16 13:32:02,523 ERROR: Exception on / [GET] [in e:\myproject\gui\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\myproject\gui\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\MyProject\Python\microblog\app\routes.py", line 29, in index
    prev_url=prev_url)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\MyProject\Python\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\MyProject\Python\microblog\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "E:\MyProject\Python\microblog\app\templates\_post.html", line 5, in top-level template code
    <img src="{{ post.author.avator(70) }}">
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avator'
2018-10-16 13:32:43,365 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:47]
2018-10-16 13:33:07,231 ERROR: Exception on /edit_profile [GET] [in e:\myproject\gui\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\myproject\gui\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\MyProject\Python\microblog\app\routes.py", line 114, in edit_profile
    return render_template('edit_profile.html',title='Edit Profile',form=form)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\MyProject\Python\microblog\app\templates\edit_profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf/html' as wtf %}
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf/html
2018-10-16 13:33:57,185 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:47]
2018-10-16 18:45:21,221 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:49]
2018-10-17 10:04:16,353 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:49]
