2019-01-02 15:37:31,721 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:86]
2019-01-02 15:43:47,598 INFO: Microblog startup [in E:\MyProject\Python\microblog\app\__init__.py:86]
2019-01-02 15:43:55,869 ERROR: Exception on /api/users/1 [GET] [in e:\myproject\gui\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\MyProject\Python\microblog\app\api\users.py", line 12, in get_user
    return jsonify(User.query.get_or_404(id).to_dict())
  File "E:\MyProject\Python\microblog\app\models.py", line 195, in to_dict
    'last_seen': self.last_seen.isoformat() + 'Z',
AttributeError: 'NoneType' object has no attribute 'isoformat'
